### ISSUE TITLE
Isolate build environment

### ISSUE THREAD

**Issue by conorsch** [freedomofpress/securedrop-keyring#1]
The package build process should be contained with a build VM, with setup scripts to install all necessary packages for the build. Having a dependency on the host machine for Vagrant is fine, then all build-specific packages can be installed inside the build VM.

**Comment by conorsch** [comment]
A vagrant VM for building is trivial here, but creating one would duplicate build tooling for the SecureDrop project. The SecureDrop repo already contains scripted build tools that reference release variables such as version number, so let's create the `securedrop-keyring` build scripts there.

**Comment by ageis** [comment]
@conorsch I think it would be more resource-efficient to run SecureDrop .deb build scripts in Docker containers.

**Comment by conorsch** [comment]
@ageis Resource constraints in the SecureDrop developer environment aren't a problem at this point in time—it currently takes about 1.5GB of RAM to run a staging environment. More importantly, we use full VMs for virtualization because the production SecureDrop deployment uses a full OS, on hardware, so using containers wouldn't provide an adequately representative test environment. Using containers strictly for building is worth considering, but would require retooling, and we already have a build VM that we can reuse to create this Debian package, as well.

**Comment by ageis** [comment]
@conorsch That's what I mean, strictly for building -- consistency with the test environment should not matter since the build environment is not a SecureDrop environment. If you really think it's worth considering I can open a pull request for this.

**Comment by conorsch** [comment]
> If you really think it's worth considering I can open a pull request for this.

No, I don't think it's worthwhile at this point in time. Going down that road would require developers to maintain two separate virtualization backends (VirtualBox and Docker or other container solution), which would require documentation and testing. We have a build VM already working and documented, so reusing those build scripts makes the most sense.

**Comment by garrettr** [comment]
In the long term, we should be moving towards using a (VM-based) system like [Gitian](https://gitian.org/) for reproducible builds. Using virtual machines makes achieving reproducibility and verifying reproducible builds across disparate platforms easier. Switching to Docker would probably yield some short-term performance improvements, but I _think_ it would be in a long-term regression in the context of achieving reproducible builds. (I would love to be proven wrong about this 😀).

**Comment by ageis** [comment]
> Using virtual machines makes achieving reproducibility and verifying reproducible builds across disparate platforms easier. 
This is true. Speaking of which, I'm presently in the midst of setting up Gitian builds and replicating the reproducible build process used by Bitcoin for [https://github.com/zcash/zcash](Zcash), so if all goes well I may have reproducibility-related work that I can modify and contribute back to you guys, assuming you don't have anyone else focusing on it right now.

**Comment by garrettr** [comment]
@ageis We don't have anybody focusing on that right now, so any and all contributions are welcome! (Especially since it's a long-standing open [issue](https://github.com/freedomofpress/securedrop/issues/308) for SecureDrop).
